### ISSUE TITLE
These lines needs to be modified, to make the license relevant & legit

### ISSUE THREAD

**Issue by r31gnf1r3** [Minds/engine#12]
Just stupid changes, but makes it legal. (i.e. put people/persons/collective or an entity whom are issuing this license, ).
https://github.com/Minds/engine/blob/c6d9c18d3e332513e7d45583eaa091bf4e7dd74c/LICENSE#L633
also line below applies.
https://github.com/Minds/engine/blob/c6d9c18d3e332513e7d45583eaa091bf4e7dd74c/LICENSE#L632

**Comment by r31gnf1r3** [comment]
also line below applies.

**Comment by markharding** [comment]
My understanding is that it is not intended to go in the license file, instead it is advising to place those notices in the READMEs and in the code.

```
It is safest
to attach them to the start of each source file to most effectively
state the exclusion of warranty; and each file should have at least
the "copyright" line and a pointer to where the full notice is found.
```
