### ISSUE TITLE
how to install it in a shared webhosting please ?

### ISSUE THREAD

**Issue by sisqi** [Minds/engine#13]
can you help me ? its for a school project thank you

**Comment by gorgabal** [comment]
I am not involved in this project, but I think that shared webhosting will not work. I strongly suspect that you need an VPS or some other complete server environment. 
You can find the instructions here: https://www.minds.org/docs/index.html . 

perhaps the project owners can comment on this?

Good luck!

**Comment by markharding** [comment]
We recommend to run Minds via Docker containers. Please checkout the compose file for more information. https://github.com/Minds/minds/blob/master/docker-compose.yml.
