### ISSUE TITLE
Publishing to Minds.com via 3rd party programs

### ISSUE THREAD

**Issue by colin-stannard** [Minds/engine#14]
I'm reasonably new to minds.com, so apologies if this is an obvious question.

Is there any kind of web API or OAuth style authentication that allows a third party program to publish content to your Minds account on your behalf? If so, is there any documentation available? Or example code?

I was looking to produce a WordPress plugin (written in PHP) that would automatically post a short summary and link to a new blog post (when the blog is published on your WordPress site). Similar WordPress plugins are already available for platforms such as Facebook.

**Comment by ottman** [comment]
Hey Colin, this is something we've been talking about for some time. Would you be interested in a quick chat next week to discuss a plan with myself and @markharding ? Thanks for your interest!

**Comment by piraz** [comment]
It wold be great to add a generic API level so we can push from other sources. I have a diaspora pod and it would be great to publish from my profile to Minds.com.

I can do that to Twitter, Tumblr, Facebook and Wordpress.

If minds can offer this kind of functionality I can work on the diaspora side to provide this the new service.

**Comment by ottman** [comment]
That's coming for sure. Let's stay in touch. What's your Minds username?

**Comment by piraz** [comment]
My username is piraz.

**Comment by DoumanAsh** [comment]
Making myself a tool to post on multiple platforms, I'm curious whether there are any concrete plans for API?
I hacked around gab.ai since they don't have API too, but if you're planning to introduce API eventually I would wait before emulating browser in my tool :D

**Comment by DoumanAsh** [comment]
I know this is not exactly proper to use internal API, but what are requirements to access `https://www.minds.com/api/v1/authenticate` ?
It seems to return ok when i supply my POST with username and password, but its response contains empty body(contrary to response in browser) and no cookies of login session.
I tried to look into engine code, and I don't exactly see a reason why such response can be received... Though I admit I'm not well familiar with php.

**Comment by markharding** [comment]
Perhaps https://github.com/Minds/mobile/blob/master/src/app/common/services/api/oauth2.ts#L35 might be relevant? We use OAuth2 for out mobile apps. Right now its limited to just username/password, but for third parties we plan on developing a console.

**Comment by DoumanAsh** [comment]
To use oauth2 I would need to have some token.
So for now my only option is to emulate browser and attempt to use `api/v1/authenticate`

**Comment by DoumanAsh** [comment]
@markharding Just wanted to re-check, you mentioned that it woulds with password/username but there are client specific info https://github.com/Minds/mobile/blob/master/src/app/common/services/api/oauth2.ts#L38-L39

Is it used or not?

**Comment by DoumanAsh** [comment]
I was able to add simple posting to my CLI tool(works also with gab.ai and twitter) https://github.com/DoumanAsh/fie - soon will make release.

**Comment by markharding** [comment]
I'm assuming this issue is resolved? Please let me know if not and I will re-open.

**Comment by belgaard** [comment]
This issue has been closed? Does that mean that we have a public API?

**Comment by Serkan-devel** [comment]
The docs aren't avilable, and I've heard something about API gees before

**Comment by DoumanAsh** [comment]
Docs are not available as Minds.com doesn't have public API, but no one stops you from using internal API.

**Comment by Serkan-devel** [comment]
*fees

**Comment by ashtonhogan** [comment]
> Docs are not available as Minds.com doesn't have public API, but no one stops you from using internal API.

@DoumanAsh are there any examples available to demonstrate available endpoints and usage?

**Comment by DoumanAsh** [comment]
@ashtonhogan If you're not afraid of Rust, you can check out my code for authentication, posting and image upload  https://github.com/DoumanAsh/fie/blob/master/src/actors/minds.rs

**Comment by Serkan-devel** [comment]
@DoumanAsh does it still work?

**Comment by DoumanAsh** [comment]
Yes, they so far hasn't changed endpoints I think(or if changed, they added only optional fields)
The API is basically JSON API so you can use your browser to verify if there are any changes to fields

**Comment by ashtonhogan** [comment]
@DoumanAsh did you happen to use postman, curl or some other plain request system to verify during the dev process by any chance?

**Comment by DoumanAsh** [comment]
no, I just used Firefox deb tools.
They are sufficient enough to view all requests

**Comment by ashtonhogan** [comment]
@DoumanAsh it doesn't really make sense though, when you create a post there's a number of requests, headers and fields that aren't clear

**Comment by DoumanAsh** [comment]
@ashtonhogan The only header that matters is `Authorization` which should be set to `Bearer <token>` which is taken from response on auth request to `https://www.minds.com/oauth2/token`

Successful authorization returns response with json that contains free fields `access_token`, `user_id` and `refresh_token`
The only thing you should care about is `access_token` as it should be includes in all other requests.

**Comment by ashtonhogan** [comment]
@DoumanAsh The only token I see in the request is `X-XSRF-TOKEN`?

**Comment by DoumanAsh** [comment]
@ashtonhogan Browser, if I'm not mistaken, uses a bit different authorization.
I relied on mobile app oauth2 endpoint so I use [Authorization](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization) header to set token

**Comment by DoumanAsh** [comment]
@ashtonhogan `Authorization` header is used to verify user instead of how browser uses `cookie` and `-x-xsrf-token`

**Comment by ashtonhogan** [comment]
@DoumanAsh So it works if you substitute `cookie` with `Authorization`? If so, how did you go about generating your jwt?

**Comment by DoumanAsh** [comment]
@ashtonhogan You need to send json to `https://www.minds.com/oauth2/token` with following fields:

```
grant_type: "password",
client_id: "",
client_secret: "",
username: <your_username>,
password: <your_password>,
```

**Comment by ashtonhogan** [comment]
@DoumanAsh Thanks, for the most part it's working now but have you ever come across this error by any chance? `{"status":"error","message":"Unknown entity type: "}`

**Comment by DoumanAsh** [comment]
Not sure? I never had such error

**Comment by ashtonhogan** [comment]
@ markharding any ideas what causes this response? `{"status":"error","message":"Unknown entity type: "}`

**Comment by ashtonhogan** [comment]
@markharding any ideas what causes this response? `{"status":"error","message":"Unknown entity type: "}`

**Comment by ashtonhogan** [comment]
@markharding @DoumanAsh Update:

if you point to `/api/v1/media/video` then the error changes from:

`{"status":"error","message":"Unknown entity type: "}`

to:

`{"status":"error","message":"Sorry, only strings and stream resource are accepted"}`

**Comment by DoumanAsh** [comment]
@ashtonhogan 

I would check how browser sends the data, I never worked with this endpoint.
Most likely you send it in incorrect format or video format is unsupported.

**Comment by ashtonhogan** [comment]
@DoumanAsh it works with `cookie` header instead of `Authorization`. Except, it expires and uploads the previous video.

**Comment by markharding** [comment]
Checkout how mobile does it here -> https://github.com/Minds/mobile-native/blob/master/src/newsfeed/Poster.js#L128

Also for reference https://github.com/Minds/mobile-native/blob/master/src/common/services/api.service.js#L168. 

Hope this helps

**Comment by ashtonhogan** [comment]
@markharding Sorry, I don't understand. I'm trying to upload a video to:

 /api/v1/media``

and I keep getting this error:

`{"status":"error","message":"Unknown entity type: "}`

Do you have a postman collection that you can share by any chance? I don't understand what the API wants. I saw you have swagger but it's not working either.

**Comment by markharding** [comment]
Yes, mobile is doing the exact same thing so I would look at that for the best implementation of this api.

**Comment by ashtonhogan** [comment]
@markharding I had a look at the links you sent. Not sure I understood though. That's uploading an image? Also, how does that help with the error I'm getting?

**Comment by Serkan-devel** [comment]
Can this issue be opened again? OP can't re-open it

**Comment by ashtonhogan** [comment]
How hard is it to write an API lol, I've written about 5000, never been this complicated

**Comment by DoumanAsh** [comment]
This is not per se official API for use per se so I'm not sure what you expect

**Comment by ashtonhogan** [comment]
Reckon I should just abort mission? Pity, cause the work I was doing would've helped minds in a big way, it was for them, not for me. Oh well, I guess in 50 years they'll have a decent social network that nobody will be using...

**Comment by jasonmayes** [comment]
Also interested in the ability to cross post. /Sub. Just migrated from Google+ and a lot of us are looking for a new home.

**Comment by plrang** [comment]
Same here (g+ refugee), the network seems interesting, so the CLEAN & FREE API would be nice

**Comment by Serkan-devel** [comment]
@plrang there aren't even API docs since 3 years it has officially launched

**Comment by plrang** [comment]
@Serkan-devel yeah, I've read something about that issue, thought my post gonna generate some more valuable information about that subject. And it did, so thank you for that

**Comment by carlcrott** [comment]
Im on this same issue. Trying to build one myself but even something as simple as a GET on the login page throws up this notification in the HTML:

https://www.minds.com/not-supported

Would love to syndicate some content into the website but even something as simple as getting the login page is returning an unsupported browser for python / requests.




Python urllib.request fails for all of the following user-agent strings:


    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36',
    'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36',
    'Mozilla/5.0 (Windows NT 5.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36',
    'Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36',
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36',
    'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36',
    'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36',
    'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36',


    'Mozilla/4.0 (compatible; MSIE 9.0; Windows NT 6.1)',
    'Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko',
    'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)',
    'Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko',
    'Mozilla/5.0 (Windows NT 6.2; WOW64; Trident/7.0; rv:11.0) like Gecko',
    'Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko',
    'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.0; Trident/5.0)',
    'Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko',
    'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)',
    'Mozilla/5.0 (Windows NT 6.1; Win64; x64; Trident/7.0; rv:11.0) like Gecko',
    'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0)',
    'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0)',
    'Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729)'

**Comment by medworthy** [comment]
@markharding, 
Why has this thread been closed, it is fairly obvious that these issues have yet to be resolved.

**Comment by carlcrott** [comment]
@medworthy are you actively working on this too?  I've managed to get logins working through the API. LMK if you'd like to compare notes.
