### ISSUE TITLE
How to Publish on Minds.com?

### ISSUE THREAD

**Issue by ThirdEyeTechnologies** [Minds/engine#19]
Hi, i am planning to make a game application where i want to fetch the minds user's full name, photo, username and display on our gaming site,  then when he want to share his play statistics on minds.com, then he can able to share it on minds directly ( caption alongwith URL )

Can i achieve this right now? Is there any API for this? 

Thank You.

**Comment by Serkan-devel** [comment]
There is an API, but no docs

**Comment by Serkan-devel** [comment]
There aren't even proper documentation to build the minds platform

**Comment by ThirdEyeTechnologies** [comment]
can you give some hints to go ahead, i would have try my best to get the stuff... OAUTH etc.
Please help me. Thank in advance.

**Comment by ThirdEyeTechnologies** [comment]
Thank You @markharding . We have some clients who want to release game on minds.com, they have it on other platforms. They are ready to pay fees too. But we don't get proper documentation. Some says its possible and some says not. If there is some work-through or code to get in. It will be good for us. If its possible to build it now, without username/pass input then let me know.

Thank You.

**Comment by markharding** [comment]
The APIs will be free to use, but we just need to develop the scope level access controls to prevent users giving full privileged access away to their accounts.

**Comment by thePerfesser** [comment]
@markharding has there been any progress on the API?

**Comment by DoumanAsh** [comment]
@markharding I don't want to create new issue for that, so I'd like to ask here, I've been using `https://www.minds.com/oauth2/token` endpoint to get Oauth token for a while now, but recently it started returning 500 response for all my requests, but I see that mobile app still uses it, I'm just wondering if anything changes with it recently
